import ArticleCourseCard from "@/Components/ArticleCourseCard";
import AuthLayout from "@/Components/Layout/AuthLayout";
import Head from "next/head";
import React from "react";

const index = () => {
  return (
    <>
      <Head>
        {/* <!-- HTML Meta Tags --> */}
        <title>Data Science: Roadmap to Success in 2023</title>
        <meta name="description" content="The need for data science has become increasingly important in today's world due to the vast amount of data being generated by businesses, organizations, and individuals. Discover the essential steps to becoming a skilled Data Scientist." />
        {/* <!-- Google / Search Engine Tags --> */}
        <meta itemProp="name" content="Data Science: Roadmap to Success in 2023" />
        <meta name="description" content="The need for data science has become increasingly important in today's world due to the vast amount of data being generated by businesses, organizations, and individuals. Discover the essential steps to becoming a skilled Data Scientist." />
        <meta itemProp="image" content="https://i.ibb.co/Jz164wH/Group-37.png" />

        {/* <!-- Facebook Meta Tags --> */}

        <meta property="og:url" content="https://edloops.com/Articles/Flutter-Roadmap" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Data Science: Roadmap to Success in 2023" />
        <meta property="og:description" content="The need for data science has become increasingly important in today's world due to the vast amount of data being generated by businesses, organizations, and individuals. Discover the essential steps to becoming a skilled Data Scientist." />
        <meta property="og:image" content="https://i.ibb.co/Jz164wH/Group-37.png" />

        {/* <!-- Twitter Meta Tags --> */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Data Science: Roadmap to Success in 2023" />
        <meta name="twitter:description" content="The need for data science has become increasingly important in today's world due to the vast amount of data being generated by businesses, organizations, and individuals. Discover the essential steps to becoming a skilled Data Scientist." />
        <meta name="twitter:image" content="https://i.ibb.co/Jz164wH/Group-37.png" />
      </Head>

      <AuthLayout>
        <div className="roadmap-structure">

          <div className="blog-Content">
            <div className="roadmap-header">
              <h1>Data Science: Roadmap to Success in 2023</h1>
              <img src="https://i.ibb.co/Jz164wH/Group-37.png" alt="datascience-roadmap" title="datascience-roadmap"/>
            </div>

            In the dynamic landscape of data science, a robust and swiftly expanding field, untapped opportunities abound. According to LinkedIn's Emerging Jobs Report, the market is poised for significant growth, projecting an increase from $37.9 billion in 2019 to a staggering $230.80 billion by 2026. Consequently, individuals aspiring to establish enduring careers in the realm of IT would be wise to consider data science as their destination. Nevertheless, the process of acquiring proficiency in a new discipline poses its challenges. Mitigating these challenges involves crafting and executing a well-defined educational plan—a roadmap.<br /> <br />
            <h2>Need for Data Scientist</h2>
            The urgency for data scientists has escalated in today's interconnected world, driven by the voluminous data generated by businesses, organizations, and individuals alike. Data science equips professionals with the tools and techniques essential for extracting meaningful insights from this data, fostering informed decision-making. This proficiency is pivotal for businesses seeking a competitive edge and improvement in operational efficiency. Furthermore, data science plays a pivotal role in addressing pressing global challenges such as healthcare, climate change, and social inequality. In essence, the demand for data science expertise is paramount in unlocking the full potential of data and making informed decisions in our data-driven era. <br /><br />
            {/* <ol>
              <> */}
                <h2 id="checkpoint1">1. Learn Python:</h2>

                Python serves as the backbone of data science. Mastering its basics is essential for seamless progression in the field. Start with the fundamentals: <br/>
    
                    1. Variables, Numbers, Strings <br />
                    2. Lists, Dictionaries, Tuples <br />
                    3. If condition, for loop <br />
                    4. Functions, modules <br />
                    5. Read, write files <br />
                    6. Exception handling <br />
                    7. Classes, Objects <br />
                    7. Numpy <br />   
                <br />
                    Resources to learn Python: <br />
                    <a href="https://www.youtube.com/watch?v=_uQrJ0TkZlc" target="_blank" rel="noopener noreferrer">Programming with Mosh</a> <br />
                    <a href="https://www.youtube.com/playlist?list=PLeo1K3hjS3uv5U-Lmlnucd7gqF-3ehIh0" target="_blank" rel="noopener noreferrer">Codebasics Python Playlist</a> first 16 videos <br /><br />
                
              
                <h2 id="checkpoint2">2. Learn Tools for Handling Data Science:</h2>

                Become proficient in essential tools like Pandas for data manipulation and Matplotlib for data visualization. These tools are the cornerstone of effective data handling and analysis in the realm of data science. <br />
                Resources to learn Pandas: 
                        <a href="https://www.youtube.com/playlist?list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS" target="_blank" rel="noopener noreferrer">Corey Schafer</a> <br />
                Resources to learn Matplotlib:
                        <a href="https://www.youtube.com/playlist?list=PLeo1K3hjS3uu4Lr8_kro2AqaO6CFYgKOl" target="_blank" rel="noopener noreferrer">Codebasics</a> <br /> <br />
             

                <h2 id="checkpoint3">3. Mathematics for Data Science:</h2>

                Understanding the mathematical foundations is crucial for unraveling the complexities of data science. Focus on key topics: <br />
                    1. Variables, Numbers, Strings <br />
                    2. Lists, Dictionaries, Tuples <br />
                    3. If condition, for loop <br />
                    4. Functions, modules <br />
                    5. Read, write files <br /> <br />
                Resources: <br />
                    Finish this excellent Khan academy course on statistics and probability<a href="https://www.khanacademy.org/math/statistics-probability" target="_blank" rel="noopener noreferrer"> Course link</a> <br />
                    Free Youtube playlist by <a href="https://www.youtube.com/playlist?list=PLeo1K3hjS3uuKaU2nBDwr6zrSOTzNCs0l" target="_blank" rel="noopener noreferrer"> Codebasics</a> <br /> <br />


            
                <h2 id="checkpoint4">4. Machine Learning:</h2>
                Delve into the exciting realm of machine learning, covering fundamental topics: <br />
                    1. Feature engineering <br />
                    2. Regression <br />
                    3. Classification <br />
                    4. Clustering <br />
                    5. Read, write files <br /> <br />
                    Resources: <br />
                    Free Youtube playlist by <a href="https://www.youtube.com/playlist?list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw" target="_blank" rel="noopener noreferrer"> Codebasics</a>  (first 21 videos only) <br /> <br />
              

             
                <h2 id="checkpoint5">5. Learn SQL:</h2>
                Data Science is all about handling of data, and as these data is stored in databases like SQL it is important to master the language of databases with a focus on practical applications:<br />
                    1. Basics of relational databases <br />
                    2. Basic Queries: SELECT, WHERE LIKE, DISTINCT, BETWEEN, GROUP BY, ORDER BY<br />
                    3. Advanced Queries: CTE, Subqueries, Window Functions<br />
                    4. Joins: Left, Right, Inner, Full<br />
                    5. Stored procedures and functions<br /> <br />
                Resources: <br />
                    One shot video <a href="https://www.youtube.com/watch?v=l8DCPaHc5TQ" target="_blank" rel="noopener noreferrer"> Chandoo</a> <br />
                    by <a href="https://www.w3schools.com/sql/" target="_blank" rel="noopener noreferrer"> w3schools</a> <br /> <br />
            
              
                <h2 id="checkpoint6">6. PowerBI Tool</h2>
                Explore the significance of PowerBI in data science. Understand its role in data visualization and the importance of hands-on projects to solidify your skills. <br />
                    OneShot video by <a href="https://www.youtube.com/watch?v=TmhQCQr_DCA" target="_blank" rel="noopener noreferrer"> Kevin Stratvert</a>  <br />
                    Personal Finance Dashboard <a href="https://www.youtube.com/watch?v=TmhQCQr_DCA" target="_blank" rel="noopener noreferrer"> Codebasics</a> <br />
                    HR Data Analytics Dashboard <a href="https://www.youtube.com/watch?v=5KaIU-9EF-0" target="_blank" rel="noopener noreferrer"> Chandoo</a> <br /> <br />
              
                    This roadmap is your guide to navigating the complexities of the field. Stay curious, practice regularly, and immerse yourself in projects to apply your knowledge. As the data science landscape evolves, your solid foundation will empower you to unlock the vast potential of data and contribute meaningfully to the ever-growing field of data science. Happy learning!
            
            <ArticleCourseCard
              imageSrc={"https://i.ibb.co/mcTQyvF/Group-37.png"}
              title={"Data Science for Beginners"}
              text={"Join 100+ users learning Flutter development"}
              linkto={"https://edloops.com/curriculum/13"}
            />
          </div>

          <div className="roadmap-path">
            <div className="checkpoint">
              <img src="/img/checkpoint.png" alt="checkpoint" />
              Checkpoint
            </div>
            <ul>
              <li><a href="#checkpoint1">1. Learn Python </a></li>
              <li><a href="#checkpoint2">2. Learn Tools for Handling Data Science</a></li>
              <li><a href="#checkpoint3">3. Mathematics for Data Science</a></li>
              <li><a href="#checkpoint4">4. Machine Learning</a></li>
              <li><a href="#checkpoint5">5. Learn SQL</a></li>
              <li><a href="#checkpoint6">6. PowerBI Tool</a></li>
            </ul>
          </div>
        </div>
      </AuthLayout>
    </>
  );
};

export default index;

