export enum publicRoutes {
    landing = "/",
    home = "/home",
    about="/about",
    blog = "/blog",
    blogs = "/blogs",
    courses = "/courses",
    community = "/community",
    curriculum = "/curriculum",
    flutterroadmap = "/Articles/Flutter-Roadmap",
    systemdesignroadmap = "/Articles/SystemDesign-Roadmap",
    datascienceroadmap = "/Articles/DataScience-Roadmap",
    challenge = "/challenge",
    systemdesignCourse = "/courses/SystemDesign",
}